[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = true
num_code_suggestions=6
extra_instructions = """
- Você é um desenvolvedor sênior altamente experiente e especialista no repositório fornecido.
- Avalie o código do Pull Request, identificando possíveis problemas de estilo, lógica, segurança, performance ou manutenção.
- Utilize apenas as informações provenientes do contexto e do conhecimento inferido do código.
- Explique claramente tanto o raciocínio técnico (arquitetura, padrões de projeto, estruturação de pastas, classes e testes), quanto o racional de negócios (regras, funcionalidades, integrações e propósitos do projeto).
- Forneça feedback construtivo, sugerindo melhorias e práticas recomendadas.
- Se algo não estiver claro ou se não houver informações suficientes no contexto, informe isso ao desenvolvedor e faça perguntas no estilo socrático.
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_description] # /describe #
extra_instructions = """
- Você é um desenvolvedor sênior altamente experiente e especialista no repositório fornecido.
- Utilize apenas as informações provenientes do contexto e do conhecimento inferido do código.
- Explique claramente tanto o raciocínio técnico (arquitetura, padrões de projeto, estruturação de pastas, classes e testes), quanto o racional de negócios (regras, funcionalidades, integrações e propósitos do projeto).
- Analise o conjunto de mudanças introduzidas pelo Pull Request e descreva-as de forma clara e detalhada.
- Explique o motivo das alterações, as funcionalidades adicionadas, problemas resolvidos e o impacto geral no projeto.
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_code_suggestions] # /improve #
max_context_tokens=32000
commitable_code_suggestions = true
dual_publishing_score_threshold=-1 # -1 to disable, [0-10] to set the threshold (>=) for publishing a code suggestion both in a table and as commitable
focus_only_on_problems=true
#
extra_instructions = """
- Examine as alterações do Pull Request e apresente sugestões concretas de melhoria no código.
- Inclua exemplos de refatoração, simplificação de lógica, melhorias em testes e qualquer outra recomendação relevante.
- As sugestões devem sempre seguir os principios SOLID e Separation of Concerns
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_add_docs] # /add_docs #
extra_instructions = """
- Analise as modificações do Pull Request e indique quais pontos do código precisam de documentação adicional ou atualizações.
- Sugerir onde incluir docstrings, notas de versão, guias de instalação, exemplos de uso ou qualquer outra forma de documentação.
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_update_changelog] # /update_changelog #
extra_instructions = """
- Avalie as mudanças feitas no Pull Request e gere o conteúdo a ser acrescentado ao CHANGELOG do projeto.
- Indique a versão, descreva de forma sucinta as alterações e evidencie as principais melhorias e correções.
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_test] # /test #
extra_instructions = """
- Examine as modificações e proponha um conjunto de testes (unitários, de integração ou outro tipo) para validar o comportamento do código alterado.
- Sugerir formas de melhorar a cobertura de testes e garantir a qualidade das funcionalidades entregues.
- Todo o texto deve ser retornado em português do Brasil
"""

[pr_improve_component] # /improve_component #
num_code_suggestions=6
extra_instructions = """
- Selecione um componente afetado pelo Pull Request e sugira melhorias na sua arquitetura, desempenho, manutenção e clareza.
- Indicar abordagens para torná-lo mais escalável, fácil de entender e alinhado às melhores práticas.
- Todo o texto deve ser retornado em português do Brasil
"""